//! Operator CLI: `init`, `add|list|get|remove` for mcp / tool / skill / tasks.
//!
//! Surface (same idea as `npm add` / Claude `mcp add`):
//! ```text
//! vmcp init
//! vmcp add mcp --transport http notion https://mcp.notion.com/mcp
//! vmcp add tool presentation build_presentation --task-support optional
//! vmcp add skill search_docs --description "…" --template "…"
//! vmcp add tasks
//! vmcp list mcp|tool|skill
//! ```
//!
//! `vmcp mcp …` remains as a thin alias for the mcp target.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use clap::{Subcommand, ValueEnum};
use vmcp_registry::{
    add_upstream, expand_upstream_spec, get_upstream, load_registry_raw, load_sidecar,
    remove_sidecar_tool, remove_upstream, save_registry_atomic, save_sidecar_atomic,
    sidecar_filename, sidecar_from_cached_tools, upsert_sidecar_tool, SidecarSpec, SidecarTool,
    TaskSupportHint, UpstreamSpec, UpstreamTransport,
};
use vmcp_server::{delete_skill, load_skills, save_skill, Skill};
use vmcp_upstream::probe_upstream_tools;

const INIT_TOML: &str = r#"# Generated by `vmcp init`. Override any key with VMCP_* env (nested via __).
# Docs: https://github.com/hewimetall/vmcp/blob/main/docs/upstreams.md

host = "127.0.0.1"
port = 8765
mcp_path = "/mcp"
public_base_url = "http://localhost:8765"

registry_path = "./registry.json"
lock_path     = "./tools.lock.json"
spec_dir      = "./specs"
skills_dir    = "./skills"

notif_ring_max = 10000

[gql]
max_depth      = 10
max_complexity = 1000

[upstream]
spawn_timeout_ms = 120000
call_timeout_ms  = 60000

[auth]
# Local scaffold: bearer off. Flip to true + hash-password for OAuth.
enabled = false

[recorder]
sessions_dir     = "./sessions"
redact_keys      = ["password", "secret", "token", "api_key", "Authorization"]
idle_ttl_secs    = 300
gc_interval_secs = 30

# Enable SEP-1686 run_task with: vmcp add tasks
# Enable flat upstream proxy with a proxy table (see docs/upstreams.md)
"#;

const INIT_REGISTRY: &str = "{\n  \"upstreams\": []\n}\n";

#[derive(Debug, Clone, Copy, ValueEnum, Default)]
pub enum CliTransport {
    #[default]
    Stdio,
    Http,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum CliTaskSupport {
    Forbidden,
    Optional,
    Required,
}

impl From<CliTaskSupport> for TaskSupportHint {
    fn from(v: CliTaskSupport) -> Self {
        match v {
            CliTaskSupport::Forbidden => TaskSupportHint::Forbidden,
            CliTaskSupport::Optional => TaskSupportHint::Optional,
            CliTaskSupport::Required => TaskSupportHint::Required,
        }
    }
}

/// `vmcp add <target>`
#[derive(Subcommand, Debug)]
pub enum AddCommand {
    /// Add an upstream MCP server to registry.json.
    ///
    /// HTTP:  `vmcp add mcp --transport http <name> <url>`
    /// stdio: `vmcp add mcp --transport stdio <name> -- <command> [args...]`
    Mcp {
        #[arg(long, value_enum, default_value_t = CliTransport::Stdio)]
        transport: CliTransport,
        #[arg(long = "env", value_name = "KEY=VALUE")]
        env: Vec<String>,
        #[arg(long)]
        bearer: Option<String>,
        #[arg(long)]
        description: Option<String>,
        #[arg(long)]
        cwd: Option<PathBuf>,
        /// Skip connect/`tools/list` — do not generate `specs/<name>.json`.
        #[arg(long)]
        no_spec: bool,
        /// Opt-in: send `X-Vmcp-Subject` / `X-Vmcp-Groups` on HTTP tool calls.
        /// For **internal** adapters only; leave off for external SaaS.
        #[arg(long)]
        forward_identity: bool,
        name: String,
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        rest: Vec<String>,
    },
    /// Upsert a sidecar tool override in `specs/<server>.json` (read_only / task_support).
    Tool {
        /// Upstream server name (must exist in registry.json).
        server: String,
        /// Tool name from upstream `tools/list`.
        tool: String,
        /// Bucket into GraphQL Query (default: Mutation / read_only=false).
        #[arg(long)]
        read_only: bool,
        /// SEP-1686 task allowlist hint for `run_task`.
        #[arg(long, value_enum)]
        task_support: Option<CliTaskSupport>,
        #[arg(long)]
        description: Option<String>,
    },
    /// Add a local skill YAML under `skills_dir` (MCP prompt playbook).
    Skill {
        name: String,
        #[arg(long)]
        description: String,
        /// Handlebars template body (required unless `--file` is set).
        #[arg(long)]
        template: Option<String>,
        /// Import an existing YAML file instead of `--template`.
        #[arg(long)]
        file: Option<PathBuf>,
    },
    /// Enable `[tasks]` in vmcp.toml (`run_task` / SEP-1686).
    Tasks,
}

/// `vmcp list <target>`
#[derive(Subcommand, Debug)]
pub enum ListCommand {
    /// List upstreams in registry.json.
    Mcp,
    /// List sidecar tool overrides (`specs/*.json`).
    Tool {
        /// Optional server filter.
        server: Option<String>,
    },
    /// List local skills in skills_dir.
    Skill,
}

/// `vmcp get <target>`
#[derive(Subcommand, Debug)]
pub enum GetCommand {
    Mcp { name: String },
    Tool { server: String, tool: String },
    Skill { name: String },
}

/// `vmcp remove <target>`
#[derive(Subcommand, Debug)]
pub enum RemoveCommand {
    Mcp { name: String },
    Tool { server: String, tool: String },
    Skill { name: String },
}

/// Legacy Claude-style `vmcp mcp <subcommand>` → mcp target.
#[derive(Subcommand, Debug)]
pub enum McpCommand {
    Add {
        #[arg(long, value_enum, default_value_t = CliTransport::Stdio)]
        transport: CliTransport,
        #[arg(long = "env", value_name = "KEY=VALUE")]
        env: Vec<String>,
        #[arg(long)]
        bearer: Option<String>,
        #[arg(long)]
        description: Option<String>,
        #[arg(long)]
        cwd: Option<PathBuf>,
        #[arg(long)]
        no_spec: bool,
        /// Opt-in identity headers for internal HTTP adapters (see `add mcp`).
        #[arg(long)]
        forward_identity: bool,
        name: String,
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        rest: Vec<String>,
    },
    List,
    Get {
        name: String,
    },
    Remove {
        name: String,
    },
}

/// Scaffold `vmcp.toml`, empty `registry.json`, and standard dirs.
pub fn run_init(dir: Option<&Path>, force: bool) -> Result<()> {
    let root = dir.unwrap_or_else(|| Path::new(".")).to_path_buf();
    fs::create_dir_all(&root).with_context(|| format!("create directory {}", root.display()))?;

    let toml_path = root.join("vmcp.toml");
    let reg_path = root.join("registry.json");
    write_new(&toml_path, INIT_TOML, force)?;
    write_new(&reg_path, INIT_REGISTRY, force)?;

    for sub in ["specs", "skills", "state", "sessions"] {
        let p = root.join(sub);
        fs::create_dir_all(&p).with_context(|| format!("create {}", p.display()))?;
    }

    eprintln!("initialized vmcp project in {}", root.display());
    eprintln!("  {}  (auth.enabled = false)", toml_path.display());
    eprintln!("  {}", reg_path.display());
    eprintln!("next (run from the project directory — paths in vmcp.toml are CWD-relative):");
    if root != Path::new(".") {
        eprintln!("  cd {}", root.display());
    }
    eprintln!("  vmcp add mcp --transport http context7 https://mcp.context7.com/mcp");
    eprintln!("  vmcp add mcp --transport stdio time -- uvx mcp-server-time");
    eprintln!("  # ↑ each add mcp probes tools/list → specs/<name>.json");
    eprintln!("  vmcp add tasks");
    eprintln!("  vmcp serve");
    Ok(())
}

fn write_new(path: &Path, contents: &str, force: bool) -> Result<()> {
    if path.exists() && !force {
        bail!(
            "{} already exists (pass --force to overwrite)",
            path.display()
        );
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn load_cfg(config: Option<&Path>) -> Result<vmcp_config::Settings> {
    vmcp_config::load(config).context("load vmcp.toml")
}

pub async fn run_add(config: Option<&Path>, cmd: AddCommand) -> Result<()> {
    match cmd {
        AddCommand::Mcp {
            transport,
            env,
            bearer,
            description,
            cwd,
            no_spec,
            forward_identity,
            name,
            rest,
        } => {
            mcp_add(
                config,
                transport,
                &name,
                &rest,
                &env,
                bearer.as_deref(),
                description,
                cwd,
                no_spec,
                forward_identity,
            )
            .await
        }
        AddCommand::Tool {
            server,
            tool,
            read_only,
            task_support,
            description,
        } => tool_add(
            config,
            &server,
            &tool,
            read_only,
            task_support.map(Into::into),
            description,
        ),
        AddCommand::Skill {
            name,
            description,
            template,
            file,
        } => skill_add(
            config,
            &name,
            &description,
            template.as_deref(),
            file.as_deref(),
        ),
        AddCommand::Tasks => tasks_enable(config),
    }
}

pub fn run_list(config: Option<&Path>, cmd: ListCommand) -> Result<()> {
    match cmd {
        ListCommand::Mcp => mcp_list(&load_cfg(config)?.registry_path),
        ListCommand::Tool { server } => tool_list(config, server.as_deref()),
        ListCommand::Skill => skill_list(config),
    }
}

pub fn run_get(config: Option<&Path>, cmd: GetCommand) -> Result<()> {
    match cmd {
        GetCommand::Mcp { name } => mcp_get(&load_cfg(config)?.registry_path, &name),
        GetCommand::Tool { server, tool } => tool_get(config, &server, &tool),
        GetCommand::Skill { name } => skill_get(config, &name),
    }
}

pub fn run_remove(config: Option<&Path>, cmd: RemoveCommand) -> Result<()> {
    match cmd {
        RemoveCommand::Mcp { name } => mcp_remove(&load_cfg(config)?.registry_path, &name),
        RemoveCommand::Tool { server, tool } => tool_remove(config, &server, &tool),
        RemoveCommand::Skill { name } => skill_remove(config, &name),
    }
}

pub async fn run_mcp(config: Option<&Path>, cmd: McpCommand) -> Result<()> {
    match cmd {
        McpCommand::Add {
            transport,
            env,
            bearer,
            description,
            cwd,
            no_spec,
            forward_identity,
            name,
            rest,
        } => {
            run_add(
                config,
                AddCommand::Mcp {
                    transport,
                    env,
                    bearer,
                    description,
                    cwd,
                    no_spec,
                    forward_identity,
                    name,
                    rest,
                },
            )
            .await
        }
        McpCommand::List => run_list(config, ListCommand::Mcp),
        McpCommand::Get { name } => run_get(config, GetCommand::Mcp { name }),
        McpCommand::Remove { name } => run_remove(config, RemoveCommand::Mcp { name }),
    }
}

#[allow(clippy::too_many_arguments)]
async fn mcp_add(
    config: Option<&Path>,
    transport: CliTransport,
    name: &str,
    rest: &[String],
    env_pairs: &[String],
    bearer: Option<&str>,
    description: Option<String>,
    cwd: Option<PathBuf>,
    no_spec: bool,
    forward_identity: bool,
) -> Result<()> {
    if matches!(transport, CliTransport::Http) {
        if !env_pairs.is_empty() {
            bail!("--env is only valid with --transport stdio");
        }
        if cwd.is_some() {
            bail!("--cwd is only valid with --transport stdio");
        }
    } else if bearer.is_some() {
        bail!("--bearer is only valid with --transport http");
    }

    let mut spec = match transport {
        CliTransport::Http => {
            let url = rest.first().map(|s| s.as_str()).unwrap_or("");
            if url.is_empty() {
                bail!("http transport requires a URL: vmcp add mcp --transport http <name> <url>");
            }
            if rest.len() > 1 {
                bail!(
                    "http transport takes a single URL argument, got extra: {:?}",
                    &rest[1..]
                );
            }
            let mut s = UpstreamSpec::http(name, url);
            if let Some(b) = bearer {
                s.bearer = Some(b.to_string());
            }
            s
        }
        CliTransport::Stdio => {
            if rest.is_empty() {
                bail!(
                    "stdio transport requires a command after `--`: \
                     vmcp add mcp --transport stdio <name> -- <command> [args...]"
                );
            }
            let command = rest[0].clone();
            let args = rest[1..].to_vec();
            let mut s = UpstreamSpec::stdio(name, command, args);
            s.cwd = cwd;
            s.env = parse_env_pairs(env_pairs)?;
            s
        }
    };
    spec.description = description;
    spec.forward_identity = forward_identity;
    if forward_identity && !matches!(transport, CliTransport::Http) {
        eprintln!("warning: --forward-identity only applies to HTTP upstreams (stdio ignores it)");
    }

    let cfg = load_cfg(config)?;
    let path = &cfg.registry_path;

    // Probe first so a failed tools/list does not leave a half-written registry.
    let generated = if no_spec {
        None
    } else {
        let expanded = expand_upstream_spec(&spec).with_context(|| {
            format!("expand env for probe `{name}` (set missing ${{VAR}} or pass --no-spec)")
        })?;
        let timeout = std::time::Duration::from_millis(cfg.upstream.spawn_timeout_ms);
        eprintln!(
            "Probing `{name}` tools/list (timeout {}ms)…",
            cfg.upstream.spawn_timeout_ms
        );
        let tools = tokio::time::timeout(timeout, probe_upstream_tools(expanded))
            .await
            .context("probe timed out — raise [upstream].spawn_timeout_ms or pass --no-spec")?
            .with_context(|| {
                format!("probe tools/list for `{name}` failed (or pass --no-spec to skip)")
            })?;
        let sc = sidecar_from_cached_tools(name, &tools);
        spec.sidecar_spec = Some(PathBuf::from(sidecar_filename(name)));
        Some(sc)
    };

    let mut reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    add_upstream(&mut reg, spec).with_context(|| format!("add upstream `{name}`"))?;
    save_registry_atomic(path, &reg).with_context(|| format!("write {}", path.display()))?;
    eprintln!(
        "Added {} MCP server `{name}` -> {}",
        transport_label(transport),
        path.display()
    );

    if let Some(sc) = generated {
        let side_path = cfg.spec_dir.join(sidecar_filename(name));
        save_sidecar_atomic(&side_path, &sc)
            .with_context(|| format!("write {}", side_path.display()))?;
        eprintln!(
            "Generated sidecar ({} tools) -> {}",
            sc.tools.len(),
            side_path.display()
        );
    } else {
        eprintln!("hint: vmcp add tool {name} <tool> [--read-only] [--task-support optional]");
    }
    if forward_identity {
        eprintln!(
            "forward_identity=true → HTTP tools/call will send X-Vmcp-Subject/Groups \
             (internal adapters only)"
        );
    }
    Ok(())
}

fn transport_label(t: CliTransport) -> &'static str {
    match t {
        CliTransport::Http => "HTTP",
        CliTransport::Stdio => "stdio",
    }
}

fn parse_env_pairs(pairs: &[String]) -> Result<BTreeMap<String, String>> {
    let mut out = BTreeMap::new();
    for p in pairs {
        let (k, v) = p
            .split_once('=')
            .with_context(|| format!("--env expects KEY=VALUE, got `{p}`"))?;
        if k.is_empty() {
            bail!("--env key must be non-empty (`{p}`)");
        }
        out.insert(k.to_string(), v.to_string());
    }
    Ok(out)
}

fn mcp_list(path: &Path) -> Result<()> {
    let reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    if reg.upstreams.is_empty() {
        eprintln!("(no upstreams in {})", path.display());
        return Ok(());
    }
    for u in &reg.upstreams {
        let detail = match u.transport {
            UpstreamTransport::Http => {
                format!("http {}", u.url.as_deref().unwrap_or("?"))
            }
            UpstreamTransport::Stdio => {
                let mut cmd = u.command.clone();
                for a in &u.args {
                    cmd.push(' ');
                    cmd.push_str(a);
                }
                format!("stdio {cmd}")
            }
        };
        let flag = if u.enabled { "" } else { " [disabled]" };
        println!("{:<24} {detail}{flag}", u.name);
    }
    Ok(())
}

fn mcp_get(path: &Path, name: &str) -> Result<()> {
    let reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    let Some(u) = get_upstream(&reg, name) else {
        bail!("unknown upstream `{name}` in {}", path.display());
    };
    println!("{}", serde_json::to_string_pretty(u)?);
    Ok(())
}

fn mcp_remove(path: &Path, name: &str) -> Result<()> {
    let mut reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    remove_upstream(&mut reg, name).with_context(|| format!("remove upstream `{name}`"))?;
    save_registry_atomic(path, &reg).with_context(|| format!("write {}", path.display()))?;
    eprintln!("Removed MCP server `{name}` from {}", path.display());
    Ok(())
}

fn sidecar_path(cfg: &vmcp_config::Settings, server: &str) -> PathBuf {
    cfg.spec_dir.join(sidecar_filename(server))
}

fn ensure_registry_sidecar_link(
    registry_path: &Path,
    server: &str,
    sidecar_rel: &str,
) -> Result<()> {
    let mut reg = load_registry_raw(registry_path)
        .with_context(|| format!("load {}", registry_path.display()))?;
    let Some(u) = reg.upstreams.iter_mut().find(|u| u.name == server) else {
        bail!("unknown upstream `{server}` — add it first: vmcp add mcp --transport … {server} …");
    };
    if u.sidecar_spec.is_none() {
        u.sidecar_spec = Some(PathBuf::from(sidecar_rel));
        save_registry_atomic(registry_path, &reg)
            .with_context(|| format!("write {}", registry_path.display()))?;
        eprintln!("Linked registry `{server}.sidecar_spec` = {sidecar_rel}");
    }
    Ok(())
}

fn tool_add(
    config: Option<&Path>,
    server: &str,
    tool: &str,
    read_only: bool,
    task_support: Option<TaskSupportHint>,
    description: Option<String>,
) -> Result<()> {
    let cfg = load_cfg(config)?;
    let path = sidecar_path(&cfg, server);
    let mut spec = load_sidecar(Some(&path))?.unwrap_or_else(|| SidecarSpec {
        server: server.to_string(),
        tools: Vec::new(),
    });
    if spec.server != server {
        bail!(
            "sidecar {} declares server `{}`, expected `{server}`",
            path.display(),
            spec.server
        );
    }
    upsert_sidecar_tool(
        &mut spec,
        SidecarTool {
            name: tool.to_string(),
            read_only,
            description,
            task_support,
        },
    );
    save_sidecar_atomic(&path, &spec).with_context(|| format!("write {}", path.display()))?;
    ensure_registry_sidecar_link(&cfg.registry_path, server, &sidecar_filename(server))?;
    eprintln!("Upserted tool `{server}.{tool}` -> {}", path.display());
    if matches!(
        task_support,
        Some(TaskSupportHint::Optional | TaskSupportHint::Required)
    ) {
        eprintln!("hint: enable run_task with `vmcp add tasks` if not already on");
    }
    Ok(())
}

fn tool_list(config: Option<&Path>, server: Option<&str>) -> Result<()> {
    let cfg = load_cfg(config)?;
    if let Some(server) = server {
        let path = sidecar_path(&cfg, server);
        let Some(spec) = load_sidecar(Some(&path))? else {
            eprintln!("(no sidecar {})", path.display());
            return Ok(());
        };
        for t in &spec.tools {
            print_tool_row(server, t);
        }
        return Ok(());
    }

    let dir = &cfg.spec_dir;
    if !dir.exists() {
        eprintln!("(no spec_dir {})", dir.display());
        return Ok(());
    }
    let mut files: Vec<_> = fs::read_dir(dir)
        .with_context(|| format!("read {}", dir.display()))?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("json"))
        .collect();
    files.sort();
    let mut any = false;
    for path in files {
        let Some(spec) = load_sidecar(Some(&path))? else {
            continue;
        };
        for t in &spec.tools {
            any = true;
            print_tool_row(&spec.server, t);
        }
    }
    if !any {
        eprintln!("(no sidecar tools in {})", dir.display());
    }
    Ok(())
}

fn print_tool_row(server: &str, t: &SidecarTool) {
    let ro = if t.read_only { "read" } else { "write" };
    let task = t.task_support.map(|h| h.as_str()).unwrap_or("-");
    println!("{server}.{:<28} {ro:<5} task={task}", t.name);
}

fn tool_get(config: Option<&Path>, server: &str, tool: &str) -> Result<()> {
    let cfg = load_cfg(config)?;
    let path = sidecar_path(&cfg, server);
    let Some(spec) = load_sidecar(Some(&path))? else {
        bail!("no sidecar {}", path.display());
    };
    let Some(t) = spec.tools.iter().find(|t| t.name == tool) else {
        bail!("unknown tool `{server}.{tool}` in {}", path.display());
    };
    println!("{}", serde_json::to_string_pretty(t)?);
    Ok(())
}

fn tool_remove(config: Option<&Path>, server: &str, tool: &str) -> Result<()> {
    let cfg = load_cfg(config)?;
    let path = sidecar_path(&cfg, server);
    let mut spec =
        load_sidecar(Some(&path))?.with_context(|| format!("no sidecar {}", path.display()))?;
    remove_sidecar_tool(&mut spec, tool)?;
    save_sidecar_atomic(&path, &spec).with_context(|| format!("write {}", path.display()))?;
    eprintln!("Removed tool `{server}.{tool}` from {}", path.display());
    Ok(())
}

fn skill_add(
    config: Option<&Path>,
    name: &str,
    description: &str,
    template: Option<&str>,
    file: Option<&Path>,
) -> Result<()> {
    let cfg = load_cfg(config)?;
    let skill = if let Some(file) = file {
        let text = fs::read_to_string(file).with_context(|| format!("read {}", file.display()))?;
        let mut s: Skill =
            serde_yaml::from_str(&text).with_context(|| format!("parse {}", file.display()))?;
        if s.name.is_empty() {
            s.name = name.to_string();
        } else if s.name != name {
            bail!("YAML name `{}` does not match CLI name `{name}`", s.name);
        }
        if s.description.is_empty() {
            s.description = description.to_string();
        }
        s
    } else {
        let template = template.unwrap_or("").trim();
        if template.is_empty() {
            bail!("skill requires --template '…' or --file path.yaml");
        }
        Skill {
            name: name.to_string(),
            description: description.to_string(),
            arguments: Vec::new(),
            template: template.to_string(),
        }
    };
    save_skill(&cfg.skills_dir, &skill).context("save skill")?;
    eprintln!(
        "Added skill `{}` -> {}/{}.yaml",
        skill.name,
        cfg.skills_dir.display(),
        skill.name
    );
    Ok(())
}

fn skill_list(config: Option<&Path>) -> Result<()> {
    let cfg = load_cfg(config)?;
    let skills = load_skills(&cfg.skills_dir)?;
    if skills.is_empty() {
        eprintln!("(no skills in {})", cfg.skills_dir.display());
        return Ok(());
    }
    for s in skills {
        println!("{:<24} {}", s.name, s.description.replace('\n', " "));
    }
    Ok(())
}

fn skill_get(config: Option<&Path>, name: &str) -> Result<()> {
    let cfg = load_cfg(config)?;
    let skills = load_skills(&cfg.skills_dir)?;
    let Some(s) = skills.into_iter().find(|s| s.name == name) else {
        bail!("unknown skill `{name}` in {}", cfg.skills_dir.display());
    };
    print!("{}", serde_yaml::to_string(&s)?);
    Ok(())
}

fn skill_remove(config: Option<&Path>, name: &str) -> Result<()> {
    let cfg = load_cfg(config)?;
    delete_skill(&cfg.skills_dir, name)?;
    eprintln!(
        "Removed skill `{name}` from {}/{name}.yaml",
        cfg.skills_dir.display()
    );
    Ok(())
}

/// Byte offset of a real TOML table header line `[name]` (ignores `# [name]` comments).
fn find_toml_table(text: &str, name: &str) -> Option<usize> {
    let header = format!("[{name}]");
    let mut offset = 0usize;
    for line in text.split_inclusive('\n') {
        if line.trim() == header {
            return Some(offset);
        }
        offset += line.len();
    }
    None
}

fn tasks_enable(config: Option<&Path>) -> Result<()> {
    let path = config
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("vmcp.toml"));
    if !path.exists() {
        bail!("{} not found — run `vmcp init` first", path.display());
    }
    let mut text = fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    if let Some(section_start) = find_toml_table(&text, "tasks") {
        let rest = &text[section_start..];
        let mut section_end = text.len();
        let mut o = 0usize;
        for line in rest.split_inclusive('\n') {
            if o > 0 {
                let t = line.trim();
                if t.starts_with('[') && t.ends_with(']') {
                    section_end = section_start + o;
                    break;
                }
            }
            o += line.len();
        }
        let section = &text[section_start..section_end];
        let has_enabled = section
            .lines()
            .any(|l| l.trim_start().starts_with("enabled") && !l.trim_start().starts_with('#'));
        if has_enabled {
            let updated = section
                .lines()
                .map(|line| {
                    let trimmed = line.trim_start();
                    if trimmed.starts_with("enabled") && !trimmed.starts_with('#') {
                        let indent = &line[..line.len() - trimmed.len()];
                        format!("{indent}enabled = true")
                    } else {
                        line.to_string()
                    }
                })
                .collect::<Vec<_>>()
                .join("\n");
            let updated = if section.ends_with('\n') && !updated.ends_with('\n') {
                format!("{updated}\n")
            } else {
                updated
            };
            text.replace_range(section_start..section_end, &updated);
        } else {
            text.insert_str(section_start + "[tasks]".len(), "\nenabled = true");
        }
    } else {
        if !text.ends_with('\n') {
            text.push('\n');
        }
        text.push_str("\n[tasks]\nenabled = true\ndb_path = \"state/tasks.db\"\n");
    }
    fs::write(&path, text).with_context(|| format!("write {}", path.display()))?;
    eprintln!("Enabled [tasks] in {}", path.display());
    eprintln!("hint: mark long tools with `vmcp add tool <server> <tool> --task-support optional`");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn tmp_dir(stem: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let p = std::env::temp_dir().join(format!("vmcp-cli-{stem}-{nanos}"));
        fs::create_dir_all(&p).unwrap();
        p
    }

    /// Rewrite scaffold paths to absolute so tests never need `chdir`
    /// (parallel tests would race on process CWD).
    fn abs_config(dir: &Path) -> PathBuf {
        let cfg = dir.join("vmcp.toml");
        let text = format!(
            r#"
host = "127.0.0.1"
port = 8765
mcp_path = "/mcp"
public_base_url = "http://localhost:8765"
registry_path = "{reg}"
lock_path     = "{lock}"
spec_dir      = "{specs}"
skills_dir    = "{skills}"
notif_ring_max = 10000

[gql]
max_depth = 10
max_complexity = 1000

[upstream]
spawn_timeout_ms = 120000
call_timeout_ms  = 60000

[auth]
enabled = false

[recorder]
sessions_dir = "{sessions}"
"#,
            reg = dir.join("registry.json").display(),
            lock = dir.join("tools.lock.json").display(),
            specs = dir.join("specs").display(),
            skills = dir.join("skills").display(),
            sessions = dir.join("sessions").display(),
        );
        fs::write(&cfg, text).unwrap();
        cfg
    }

    #[tokio::test]
    async fn init_add_mcp_tool_skill_tasks() {
        let dir = tmp_dir("full");
        run_init(Some(&dir), false).unwrap();
        let cfg = abs_config(&dir);

        // Fake command — skip probe; tool upsert covers sidecar path.
        run_add(
            Some(&cfg),
            AddCommand::Mcp {
                transport: CliTransport::Stdio,
                env: vec![],
                bearer: None,
                description: None,
                cwd: None,
                no_spec: true,
                forward_identity: false,
                name: "presentation".into(),
                rest: vec!["uvx".into(), "mcp-presentation".into()],
            },
        )
        .await
        .unwrap();
        run_add(
            Some(&cfg),
            AddCommand::Tool {
                server: "presentation".into(),
                tool: "build_presentation".into(),
                read_only: false,
                task_support: Some(CliTaskSupport::Optional),
                description: None,
            },
        )
        .await
        .unwrap();
        run_add(
            Some(&cfg),
            AddCommand::Skill {
                name: "build".into(),
                description: "Build a deck".into(),
                template: Some("Call run_task for build_presentation".into()),
                file: None,
            },
        )
        .await
        .unwrap();
        run_add(Some(&cfg), AddCommand::Tasks).await.unwrap();

        let reg = load_registry_raw(&dir.join("registry.json")).unwrap();
        assert!(!reg.upstreams[0].forward_identity);
        assert_eq!(
            reg.upstreams[0].sidecar_spec.as_deref(),
            Some(Path::new("presentation.json"))
        );
        let sc = load_sidecar(Some(&dir.join("specs/presentation.json")))
            .unwrap()
            .unwrap();
        assert_eq!(sc.tools[0].name, "build_presentation");
        assert_eq!(sc.tools[0].task_support, Some(TaskSupportHint::Optional));
        assert!(dir.join("skills/build.yaml").exists());
        let toml = fs::read_to_string(&cfg).unwrap();
        assert!(
            toml.lines().any(|l| l.trim() == "[tasks]"),
            "expected real [tasks] table, got:\n{toml}"
        );
        assert!(toml.lines().any(|l| l.trim() == "enabled = true"));

        run_remove(
            Some(&cfg),
            RemoveCommand::Tool {
                server: "presentation".into(),
                tool: "build_presentation".into(),
            },
        )
        .unwrap();
        run_remove(
            Some(&cfg),
            RemoveCommand::Skill {
                name: "build".into(),
            },
        )
        .unwrap();

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn init_refuses_overwrite_without_force() {
        let dir = tmp_dir("noforce");
        run_init(Some(&dir), false).unwrap();
        let err = run_init(Some(&dir), false).unwrap_err();
        assert!(err.to_string().contains("--force"));
        run_init(Some(&dir), true).unwrap();
        let _ = fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn mcp_alias_still_works() {
        let dir = tmp_dir("alias");
        run_init(Some(&dir), false).unwrap();
        let cfg = abs_config(&dir);
        run_mcp(
            Some(&cfg),
            McpCommand::Add {
                transport: CliTransport::Http,
                env: vec![],
                bearer: None,
                description: None,
                cwd: None,
                no_spec: true,
                forward_identity: false,
                name: "notion".into(),
                rest: vec!["https://mcp.notion.com/mcp".into()],
            },
        )
        .await
        .unwrap();
        let reg = load_registry_raw(&dir.join("registry.json")).unwrap();
        assert_eq!(reg.upstreams[0].name, "notion");
        assert!(!reg.upstreams[0].forward_identity);

        // Internal adapter: opt-in identity forwarding.
        run_add(
            Some(&cfg),
            AddCommand::Mcp {
                transport: CliTransport::Http,
                env: vec![],
                bearer: None,
                description: Some("cluster stand adapter".into()),
                cwd: None,
                no_spec: true,
                forward_identity: true,
                name: "stand_api".into(),
                rest: vec!["http://stand-api.internal/mcp".into()],
            },
        )
        .await
        .unwrap();
        let reg = load_registry_raw(&dir.join("registry.json")).unwrap();
        let stand = reg
            .upstreams
            .iter()
            .find(|u| u.name == "stand_api")
            .unwrap();
        assert!(stand.forward_identity);

        let _ = fs::remove_dir_all(&dir);
    }
}
