//! Operator CLI helpers: `vmcp init` and `vmcp mcp …` (Claude-style).
//!
//! Registry mutations load/save via [`vmcp_registry::load_registry_raw`] so
//! `${ENV}` placeholders are not expanded on round-trip.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use clap::{Subcommand, ValueEnum};
use vmcp_registry::{
    add_upstream, get_upstream, load_registry_raw, remove_upstream, save_registry_atomic,
    UpstreamSpec, UpstreamTransport,
};

const INIT_TOML: &str = r#"# Generated by `vmcp init`. Override any key with VMCP_* env (nested via __).
# Docs: https://github.com/hewimetall/vmcp/blob/main/docs/upstreams.md

host = "127.0.0.1"
port = 8765
mcp_path = "/mcp"
public_base_url = "http://localhost:8765"

registry_path = "./registry.json"
lock_path     = "./tools.lock.json"
spec_dir      = "./specs"
skills_dir    = "./skills"

notif_ring_max = 10000

[gql]
max_depth      = 10
max_complexity = 1000

[upstream]
spawn_timeout_ms = 120000
call_timeout_ms  = 60000

[auth]
# Local scaffold: bearer off. Flip to true + hash-password for OAuth.
enabled = false

[recorder]
sessions_dir     = "./sessions"
redact_keys      = ["password", "secret", "token", "api_key", "Authorization"]
idle_ttl_secs    = 300
gc_interval_secs = 30
"#;

const INIT_REGISTRY: &str = "{\n  \"upstreams\": []\n}\n";

#[derive(Debug, Clone, Copy, ValueEnum, Default)]
pub enum CliTransport {
    #[default]
    Stdio,
    Http,
}

impl From<CliTransport> for UpstreamTransport {
    fn from(value: CliTransport) -> Self {
        match value {
            CliTransport::Stdio => UpstreamTransport::Stdio,
            CliTransport::Http => UpstreamTransport::Http,
        }
    }
}

#[derive(Subcommand, Debug)]
pub enum McpCommand {
    /// Add an upstream to registry.json (Claude-style syntax).
    ///
    /// HTTP:  `vmcp mcp add --transport http <name> <url>`
    /// stdio: `vmcp mcp add --transport stdio <name> -- <command> [args...]`
    Add {
        /// Transport: `stdio` (default) or `http`.
        #[arg(long, value_enum, default_value_t = CliTransport::Stdio)]
        transport: CliTransport,
        /// Environment `KEY=VALUE` for the stdio child (repeatable).
        #[arg(long = "env", value_name = "KEY=VALUE")]
        env: Vec<String>,
        /// Bearer token (or `${ENV}`) for HTTP upstreams.
        #[arg(long)]
        bearer: Option<String>,
        /// Operator description shown in `Query.servers`.
        #[arg(long)]
        description: Option<String>,
        /// Working directory for stdio child.
        #[arg(long)]
        cwd: Option<PathBuf>,
        /// Logical upstream name (GraphQL namespace).
        name: String,
        /// HTTP: URL. Stdio: command + args (put after `--`).
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        rest: Vec<String>,
    },
    /// List upstreams in registry.json.
    List,
    /// Show one upstream as JSON.
    Get {
        name: String,
    },
    /// Remove an upstream by name.
    Remove {
        name: String,
    },
}

/// Scaffold `vmcp.toml`, empty `registry.json`, and standard dirs.
pub fn run_init(dir: Option<&Path>, force: bool) -> Result<()> {
    let root = dir.unwrap_or_else(|| Path::new(".")).to_path_buf();
    fs::create_dir_all(&root)
        .with_context(|| format!("create directory {}", root.display()))?;

    let toml_path = root.join("vmcp.toml");
    let reg_path = root.join("registry.json");
    write_new(&toml_path, INIT_TOML, force)?;
    write_new(&reg_path, INIT_REGISTRY, force)?;

    for sub in ["specs", "skills", "state", "sessions"] {
        let p = root.join(sub);
        fs::create_dir_all(&p).with_context(|| format!("create {}", p.display()))?;
    }

    eprintln!("initialized vmcp project in {}", root.display());
    eprintln!("  {}  (auth.enabled = false)", toml_path.display());
    eprintln!("  {}", reg_path.display());
    eprintln!("next:");
    eprintln!("  vmcp mcp add --transport http context7 https://mcp.context7.com/mcp");
    eprintln!("  vmcp mcp add --transport stdio time -- uvx mcp-server-time");
    eprintln!("  vmcp --config {}/vmcp.toml serve", root.display());
    Ok(())
}

fn write_new(path: &Path, contents: &str, force: bool) -> Result<()> {
    if path.exists() && !force {
        bail!(
            "{} already exists (pass --force to overwrite)",
            path.display()
        );
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

/// Resolve `registry_path` from `--config` / defaults.
pub fn registry_path(config: Option<&Path>) -> Result<PathBuf> {
    let cfg = vmcp_config::load(config)?;
    Ok(cfg.registry_path)
}

pub fn run_mcp(config: Option<&Path>, cmd: McpCommand) -> Result<()> {
    let path = registry_path(config)?;
    match cmd {
        McpCommand::Add {
            transport,
            env,
            bearer,
            description,
            cwd,
            name,
            rest,
        } => mcp_add(
            &path,
            transport,
            &name,
            &rest,
            &env,
            bearer.as_deref(),
            description,
            cwd,
        ),
        McpCommand::List => mcp_list(&path),
        McpCommand::Get { name } => mcp_get(&path, &name),
        McpCommand::Remove { name } => mcp_remove(&path, &name),
    }
}

#[allow(clippy::too_many_arguments)]
fn mcp_add(
    path: &Path,
    transport: CliTransport,
    name: &str,
    rest: &[String],
    env_pairs: &[String],
    bearer: Option<&str>,
    description: Option<String>,
    cwd: Option<PathBuf>,
) -> Result<()> {
    if matches!(transport, CliTransport::Http) {
        if !env_pairs.is_empty() {
            bail!("--env is only valid with --transport stdio");
        }
        if cwd.is_some() {
            bail!("--cwd is only valid with --transport stdio");
        }
    } else if bearer.is_some() {
        bail!("--bearer is only valid with --transport http");
    }

    let mut spec = match transport {
        CliTransport::Http => {
            let url = rest.first().map(|s| s.as_str()).unwrap_or("");
            if url.is_empty() {
                bail!("http transport requires a URL: vmcp mcp add --transport http <name> <url>");
            }
            if rest.len() > 1 {
                bail!(
                    "http transport takes a single URL argument, got extra: {:?}",
                    &rest[1..]
                );
            }
            let mut s = UpstreamSpec::http(name, url);
            if let Some(b) = bearer {
                s.bearer = Some(b.to_string());
            }
            s
        }
        CliTransport::Stdio => {
            if rest.is_empty() {
                bail!(
                    "stdio transport requires a command after `--`: \
                     vmcp mcp add --transport stdio <name> -- <command> [args...]"
                );
            }
            let command = rest[0].clone();
            let args = rest[1..].to_vec();
            let mut s = UpstreamSpec::stdio(name, command, args);
            s.cwd = cwd;
            s.env = parse_env_pairs(env_pairs)?;
            s
        }
    };
    spec.description = description;

    let mut reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    add_upstream(&mut reg, spec).with_context(|| format!("add upstream `{name}`"))?;
    save_registry_atomic(path, &reg).with_context(|| format!("write {}", path.display()))?;
    eprintln!("Added {} MCP server `{name}` -> {}", transport_label(transport), path.display());
    Ok(())
}

fn transport_label(t: CliTransport) -> &'static str {
    match t {
        CliTransport::Http => "HTTP",
        CliTransport::Stdio => "stdio",
    }
}

fn parse_env_pairs(pairs: &[String]) -> Result<BTreeMap<String, String>> {
    let mut out = BTreeMap::new();
    for p in pairs {
        let (k, v) = p.split_once('=').with_context(|| {
            format!("--env expects KEY=VALUE, got `{p}`")
        })?;
        if k.is_empty() {
            bail!("--env key must be non-empty (`{p}`)");
        }
        out.insert(k.to_string(), v.to_string());
    }
    Ok(out)
}

fn mcp_list(path: &Path) -> Result<()> {
    let reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    if reg.upstreams.is_empty() {
        eprintln!("(no upstreams in {})", path.display());
        return Ok(());
    }
    for u in &reg.upstreams {
        let detail = match u.transport {
            UpstreamTransport::Http => {
                format!("http {}", u.url.as_deref().unwrap_or("?"))
            }
            UpstreamTransport::Stdio => {
                let mut cmd = u.command.clone();
                for a in &u.args {
                    cmd.push(' ');
                    cmd.push_str(a);
                }
                format!("stdio {cmd}")
            }
        };
        let flag = if u.enabled { "" } else { " [disabled]" };
        println!("{:<24} {detail}{flag}", u.name);
    }
    Ok(())
}

fn mcp_get(path: &Path, name: &str) -> Result<()> {
    let reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    let Some(u) = get_upstream(&reg, name) else {
        bail!("unknown upstream `{name}` in {}", path.display());
    };
    println!("{}", serde_json::to_string_pretty(u)?);
    Ok(())
}

fn mcp_remove(path: &Path, name: &str) -> Result<()> {
    let mut reg = load_registry_raw(path).with_context(|| format!("load {}", path.display()))?;
    remove_upstream(&mut reg, name)
        .with_context(|| format!("remove upstream `{name}`"))?;
    save_registry_atomic(path, &reg).with_context(|| format!("write {}", path.display()))?;
    eprintln!("Removed MCP server `{name}` from {}", path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn tmp_dir(stem: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let p = std::env::temp_dir().join(format!("vmcp-cli-{stem}-{nanos}"));
        fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn init_then_add_http_and_stdio() {
        let dir = tmp_dir("init");
        run_init(Some(&dir), false).unwrap();
        assert!(dir.join("vmcp.toml").exists());
        assert!(dir.join("registry.json").exists());

        let cfg = dir.join("vmcp.toml");
        run_mcp(
            Some(&cfg),
            McpCommand::Add {
                transport: CliTransport::Http,
                env: vec![],
                bearer: Some("${CTX_KEY}".into()),
                description: Some("docs".into()),
                cwd: None,
                name: "context7".into(),
                rest: vec!["https://mcp.context7.com/mcp".into()],
            },
        )
        .unwrap();
        run_mcp(
            Some(&cfg),
            McpCommand::Add {
                transport: CliTransport::Stdio,
                env: vec!["TZ=UTC".into()],
                bearer: None,
                description: None,
                cwd: None,
                name: "time".into(),
                rest: vec!["uvx".into(), "mcp-server-time".into()],
            },
        )
        .unwrap();

        let reg = load_registry_raw(&dir.join("registry.json")).unwrap();
        assert_eq!(reg.upstreams.len(), 2);
        assert_eq!(
            reg.upstreams[0].bearer.as_deref(),
            Some("${CTX_KEY}")
        );
        assert_eq!(reg.upstreams[1].command, "uvx");
        assert_eq!(reg.upstreams[1].env.get("TZ").map(String::as_str), Some("UTC"));

        run_mcp(
            Some(&cfg),
            McpCommand::Remove {
                name: "context7".into(),
            },
        )
        .unwrap();
        let reg = load_registry_raw(&dir.join("registry.json")).unwrap();
        assert_eq!(reg.upstreams.len(), 1);
        assert_eq!(reg.upstreams[0].name, "time");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn init_refuses_overwrite_without_force() {
        let dir = tmp_dir("noforce");
        run_init(Some(&dir), false).unwrap();
        let err = run_init(Some(&dir), false).unwrap_err();
        assert!(err.to_string().contains("--force"));
        run_init(Some(&dir), true).unwrap();
        let _ = fs::remove_dir_all(&dir);
    }
}
